Prune Changes
JuliaPOMDP/NativeSARSOP.jl pull request #19
Opened 2024-06-28 23:16 UTC by dylan-asmar

This PR introduces some changes to the pruning process. The changes don't address witness pruning or adapting the delta parameters, but it implements some changes to the `prune_alpha!` function and adds in a method to prune strictly dominated alpha vectors (comparing vectors only, not at specific belief points). 

The original `intersection_distance` implementation did not return the actual distance from the alpha vectors intersection to the belief point. The original implmenation took advantage of the sparsity of the belief vector and only calcualted the demoninator (the squared difference of the alpha vectors) for non-zero values of the belief vector. This was a good idea for speed, but I think it was an error. For example, check what the original function would return if you had `[1.0, 0.0]` for `a1`, `[0.0, 1.0]` for `a2`, and `[0.5, 0.5]` for `b`. The function would return `1.0` as the distance, but the actual distance is `0.5`. This PR has a revised implementation. It is a bit slower, but returns a more accurate distance.

Based on the slightly slower distance calcualtion, I also `prune_strictly_dominated!(::SARSOPTree)` to prune strictly dominated alpha vectors. This fuction removes any vectors that are dominated across the entire belief space (by just comparing the values of the vectors, not at specific belief points). This function is called in `prune!(::SARSOPSolver, ::SARSOPTree)` after the beleifs are pruned. This addition ended up speeding up the process a bit and almost made up for the the slower distance callculation (still saw some slower times in the larger proboems, e.g. RockSample(15,10)).

The last change is to `prune_alpha!`. Instead of looping through each vector and then checking at all belief points, we now first check for the dominating alpha vectors at each belief point. Then we only need to compare the dominated alpha vector at each point to all other vectors to check for delta dominance. This change doesn't catch duplicate alpha vectors, but the added `prune_strictly_dominated!` function catches those. This method also sets up the framework towards an adaptive delta implementation ([related issue](https://github.com/JuliaPOMDP/NativeSARSOP.jl/issues/2)) as we need to track which belief points each vector is dominated at.

I did some ablation studies for each change. However, I am only included the final performance comparisons here for different delta values. The only hit in performance is RockSample(5,5), but the larger problems see a decent performance increase.

# Performance Comparison (delta = 0.1)
## BabyPOMDP
Settings:
  - epsilon: 0.1
  - precision: 0.001
  - delta: 0.1
  - max_steps: 50 (for benchmarking)
  - max_time: 5.0 (for policy run)
### Benchmark
#### Original
```julia
BenchmarkTools.Trial: 3171 samples with 1 evaluation.
 Range (min … max):  1.505 ms …  43.395 ms  ┊ GC (min … max): 0.00% … 96.20%
 Time  (median):     1.537 ms               ┊ GC (median):    0.00%
 Time  (mean ± σ):   1.575 ms ± 773.872 μs  ┊ GC (mean ± σ):  1.94% ±  5.34%

    ▂▇██▆▆▃▅▅▃▂▁                                               
  ▃▆████████████▇▆▆▆▅▄▅▄▅▃▄▃▃▃▃▃▃▃▂▂▂▃▂▃▂▂▂▂▁▂▂▂▂▂▂▂▂▂▂▁▂▂▂▂▂ ▄
  1.51 ms         Histogram: frequency by time         1.7 ms <

 Memory estimate: 425.98 KiB, allocs estimate: 3847.
```
#### New
```julia
BenchmarkTools.Trial: 2745 samples with 1 evaluation.
 Range (min … max):  1.703 ms …  44.417 ms  ┊ GC (min … max): 0.00% … 95.84%
 Time  (median):     1.747 ms               ┊ GC (median):    0.00%
 Time  (mean ± σ):   1.820 ms ± 893.154 μs  ┊ GC (mean ± σ):  3.45% ±  8.04%

  █▇▄▂                                                         
  ████▇▇▆▃▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▄▄▆▅▅▅ █
  1.7 ms       Histogram: log(frequency) by time      4.54 ms <

 Memory estimate: 871.79 KiB, allocs estimate: 16157.
```
### Policy Run
#### Original
```julia
--------------------------------------------------------------------------------------
 Time       Iter       LB           UB           Precision       # Alphas   # Beliefs 
--------------------------------------------------------------------------------------
 0.00       0          -28.3501795  -15.6037314  12.7464480985   3          30        
 0.00       10         -16.3057342  -16.2819897  0.0237444537    2          98        
 0.00       20         -16.3054833  -16.3024060  0.0030772894    2          133       
--------------------------------------------------------------------------------------
 0.00       28         -16.3054833  -16.3045949  0.0008883805    2          134       
--------------------------------------------------------------------------------------
```
#### New
```julia
--------------------------------------------------------------------------------------
 Time       Iter       LB           UB           Precision       # Alphas   # Beliefs 
--------------------------------------------------------------------------------------
 0.00       0          -28.3501795  -15.6037314  12.7464480985   3          30        
 0.00       10         -16.3057342  -16.2819897  0.0237444537    2          98        
 0.00       20         -16.3054833  -16.3024060  0.0030772894    2          133       
--------------------------------------------------------------------------------------
 0.00       28         -16.3054833  -16.3045949  0.0008883805    2          134       
--------------------------------------------------------------------------------------
```
## TigerPOMDP
Settings:
  - epsilon: 0.1
  - precision: 0.001
  - delta: 0.1
  - max_steps: 50 (for benchmarking)
  - max_time: 5.0 (for policy run)
### Benchmark
#### Original
```julia
BenchmarkTools.Trial: 175 samples with 1 evaluation.
 Range (min … max):  27.593 ms … 68.988 ms  ┊ GC (min … max): 0.00% … 59.07%
 Time  (median):     28.125 ms              ┊ GC (median):    0.00%
 Time  (mean ± σ):   28.701 ms ±  3.273 ms  ┊ GC (mean ± σ):  1.37% ±  4.96%

   ▂ ▃▄▂█▂▁▁                                                   
  ▄█████████▅▅▅▄▄▄▃▃▁▁▃▁▄▅▃▃▃▁▁▁▃▁▁▁▁▃▁▁▃▃▁▁▁▁▁▁▁▃▁▁▃▃▁▃▁▁▃▁▃ ▃
  27.6 ms         Histogram: frequency by time        32.1 ms <

 Memory estimate: 3.99 MiB, allocs estimate: 30581.
```
#### New
```julia
BenchmarkTools.Trial: 182 samples with 1 evaluation.
 Range (min … max):  26.610 ms … 70.520 ms  ┊ GC (min … max): 0.00% … 61.16%
 Time  (median):     26.960 ms              ┊ GC (median):    0.00%
 Time  (mean ± σ):   27.593 ms ±  3.378 ms  ┊ GC (mean ± σ):  1.69% ±  5.27%

   ▂█▃▄                                                        
  ▄█████▇▂▄▄▄▂▃▂▄▃▂▁▄▂▁▃▂▃▂▁▁▂▁▁▁▁▁▁▁▂▁▁▃▂▁▁▂▂▁▃▁▂▁▃▂▁▁▁▁▁▁▁▂ ▂
  26.6 ms         Histogram: frequency by time        31.2 ms <

 Memory estimate: 4.84 MiB, allocs estimate: 74354.
```
### Policy Run
#### Original
```julia
--------------------------------------------------------------------------------------
 Time       Iter       LB           UB           Precision       # Alphas   # Beliefs 
--------------------------------------------------------------------------------------
 0.00       0          -10.7779872  87.0980496   97.8760368879   7          44        
 0.01       10         14.2589622   51.5049954   37.2460332328   5          464       
 0.01       20         18.6214722   33.7498003   15.1283280569   5          649       
 0.02       30         19.3534084   21.8312080   2.4777995367    5          657       
 0.02       40         19.3709835   19.6684906   0.2975071211    5          463       
 0.03       50         19.3713674   19.3833253   0.0119579046    6          212       
--------------------------------------------------------------------------------------
 0.04       57         19.3713684   19.3722266   0.0008581957    6          467       
--------------------------------------------------------------------------------------
```
#### New
```julia
--------------------------------------------------------------------------------------
 Time       Iter       LB           UB           Precision       # Alphas   # Beliefs 
--- [...]

2024-07-09 21:30 UTC, WhiffleFish commented
Thanks for the PR! You're entirely correct, the current intersection distance implementation is wrong. However, I think the significant increase in allocations here needs to be addressed.

2024-07-09 22:15 UTC, WhiffleFish requested changes
This PR is absolutely necessary -- I do however think it needs to be a bit more performant before a merge.

Great work

2024-07-10 05:32 UTC, dylan-asmar commented on src/prune.jl
> +end
Interesting. I looked at the implementation for `dot` but didn't consider removing `diff` for performance. It is crazy how things like that add up!

2024-07-10 05:35 UTC, dylan-asmar commented on src/prune.jl
> +    prune_strictly_dominated!(tree::SARSOPTree)
I do remember considering this, but I don't remember the details when I compared the two. I can run some comparisons and report back. (timeline TBD)

2024-07-22 19:53 UTC, dylan-asmar commented on src/prune.jl
> +    prune_strictly_dominated!(tree::SARSOPTree)
TL;DR; I'd recommend keeping it as pruning at every iteration.

Just ran the comparison for `delta=1e-4`. The allocations are a bit higher when running at every iteration, but the overall process is faster. The difference between these benchmarks and the original ones posted at the submission of hr PR is due to the suggested changes (which help out quite a bit!).

## BabyPOMDP
Settings:
  - epsilon: 0.1
  - precision: 0.001
  - delta: 0.0001
  - max_steps: 50 (for benchmarking)
  - max_time: 5.0 (for policy run)
### Benchmark
#### At Every Iteration
```julia
BenchmarkTools.Trial: 3262 samples with 1 evaluation.
 Range (min … max):  1.384 ms … 69.646 ms  ┊ GC (min … max): 0.00% … 97.80%
 Time  (median):     1.423 ms              ┊ GC (median):    0.00%
 Time  (mean ± σ):   1.531 ms ±  1.607 ms  ┊ GC (mean ± σ):  3.23% ±  6.40%

  █▆▅▄▂                                                      ▁
  ██████▆▆▅▅▅▅▃▁▃▁▁▃▁▁▁▁▁▁▃▄▁▁▁▁▁▁▁▁▁▁▁▁▁▃▃▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▃▃ █
  1.38 ms      Histogram: log(frequency) by time     3.84 ms <

 Memory estimate: 662.32 KiB, allocs estimate: 8721.
```
#### Only when `should_prune_alphas`
```julia
BenchmarkTools.Trial: 3284 samples with 1 evaluation.
 Range (min … max):  1.420 ms … 68.969 ms  ┊ GC (min … max): 0.00% … 97.74%
 Time  (median):     1.456 ms              ┊ GC (median):    0.00%
 Time  (mean ± σ):   1.521 ms ±  1.236 ms  ┊ GC (mean ± σ):  3.64% ±  6.95%

    ▁▇█▄▂   ▁                                                 
  ▂▅██████▇████▆▆▆▄▄▄▃▄▃▃▃▃▃▃▃▃▃▃▂▂▂▂▂▃▂▂▂▂▂▂▂▂▂▂▂▂▁▂▁▁▁▁▁▂▂ ▃
  1.42 ms        Histogram: frequency by time        1.67 ms <

 Memory estimate: 771.65 KiB, allocs estimate: 9099.
```
### Policy Run
#### At Every Iteration
```julia
--------------------------------------------------------------------------------------
 Time       Iter       LB           UB           Precision       # Alphas   # Beliefs 
--------------------------------------------------------------------------------------
 0.00       0          -28.3501795  -15.6037314  12.7464480985   2          30        
 0.00       10         -16.3057342  -16.2819897  0.0237444537    2          98        
 0.00       20         -16.3054833  -16.3024060  0.0030772894    2          133       
--------------------------------------------------------------------------------------
 0.00       28         -16.3054833  -16.3045949  0.0008883805    2          134       
--------------------------------------------------------------------------------------
```
#### Only when `should_prune_alphas`
```julia
--------------------------------------------------------------------------------------
 Time       Iter       LB           UB           Precision       # Alphas   # Beliefs 
--------------------------------------------------------------------------------------
 0.00       0          -28.3501795  -15.6037314  12.7464480985   2          30        
 0.00       10         -16.3057342  -16.2819897  0.0237444537    2          98        
 0.00       20         -16.3054833  -16.3024060  0.0030772894    2          133       
--------------------------------------------------------------------------------------
 0.00       28         -16.3054833  -16.3045949  0.0008883805    2          134       
--------------------------------------------------------------------------------------
```
## TigerPOMDP
Settings:
  - epsilon: 0.1
  - precision: 0.001
  - delta: 0.0001
  - max_steps: 50 (for benchmarking)
  - max_time: 5.0 (for policy run)
### Benchmark
#### At Every Iteration
```julia
BenchmarkTools.Trial: 188 samples with 1 evaluation.
 Range (min … max):  25.590 ms … 94.617 ms  ┊ GC (min … max): 0.00% … 71.50%
 Time  (median):     26.162 ms              ┊ GC (median):    0.00%
 Time  (mean ± σ):   26.683 ms ±  5.040 ms  ┊ GC (mean ± σ):  1.70% ±  5.60%

   ▁ ▂▅▆██▅▁                                                   
  ▆█▇███████▁▅█▆▅▆▅▁▅▅▁▁▁▅▁▁▁▅▁▁▅▁▁▁▅▅▅▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▅▅▁▁▁▅ ▅
  25.6 ms      Histogram: log(frequency) by time      30.5 ms <

 Memory estimate: 4.02 MiB, allocs estimate: 39898.
```
#### Only when `should_prune_alphas`
```julia
BenchmarkTools.Trial: 184 samples with 1 evaluation.
 Range (min … max):  26.127 ms … 91.703 ms  ┊ GC (min … max): 0.00% … 71.08%
 Time  (median):     26.702 ms              ┊ GC (median):    0.00%
 Time  (mean ± σ):   27.259 ms ±  4.871 ms  ┊ GC (mean ± σ):  1.89% ±  5.92%

      ▄▇█▆                                                     
  ▆▄▆██████▆▇▇▁▆▄█▁▁▆▁▄▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▄▆▁▁▁▁▄▄ ▄
  26.1 ms      Histogram: log(frequency) by time      31.5 ms <

 Memory estimate: 4.81 MiB, allocs estimate: 40544.
```
### Policy Run
#### At Every Iteration
```julia
--------------------------------------------------------------------------------------
 Time       Iter       LB           UB           Precision       # Alphas   # Beliefs 
--------------------------------------------------------------------------------------
 0.00       0          -10.7779872  87.0980496   97.8760368879   6          44        
 0.01       10         14.2589622   51.5049954   37.2460332328   5          464       
...     
 0.02       40         19.3709835   19.6684906   0.2975071211    5          463       
 0.03       50         19.3713674   19.3833253   0.0119579046    5          212       
--------------------------------------------------------------------------------------
 0.03       57         19.3713684   19.3722266   0.0008581957    5          467       
--------------------------------------------------------------------------------------
```
#### Only when `should_prune_alphas`
```julia
--------------------------------------------------------------------------------------
 Time       Iter       LB           UB           Precision       # Alphas   # Beliefs 
--------------------------------------------------------------------------------------
 0.00       0          -10.7779872  87.0980496   97.8760368879   6          44        
 0.01       10         14.2589622   51.5049954   37.2460332328   5          464       
...      
 0.02       40         19.3709835   19.6684906   0.2975071211    5          463       
 0.03       50         19.3713674   19.3833253   0.0119579046    5          212       
--------------------------------------------------------------------------------------
 0.03       57         19.3713684   19.3722266   0.0008581957    5          467       
--------------------------------------------------------------------------------------
```
## RockSamplePOMDP(5,5)
Settings:
  - epsilon: 0.1
  - precision: 0.001
  - delta: 0.0001
  - max_steps: 50 (for benchmarking)
  - max_time: 5.0 (for policy run)
### Benchmark
#### At Every Iteration
```julia
BenchmarkTools.Trial: 235 samples with 1 evaluation.
 Range (min … max):  19.918 ms … 94.401 ms  ┊ GC (min … max): 0.00% … 77.84%
 Time  (median):     20.551 ms              ┊ GC (median):    0.00%
 Time  (mean ± σ):   21.292 ms ±  4.979 ms  ┊ GC (mean ± σ):  3.92% ±  7.37%

  ▁▄▅▆▄▄▆█▃▁▁ ▁                                                
  ███████████▅█▇▇▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▅▁▅▆▅▅▁▆▆▆▅█▁▇▁▅▁▁▆▅▆▅▅▁▇ ▆
  19.9 ms      Histogram: log(frequency) by time      25.3 ms <

 Memory estimate: 11.77 MiB, allocs estimate: 51341.
```
#### Only when `should_prune_alphas`
```julia
BenchmarkTools.Trial: 227 samples with 1 evaluation.
 Range (min … max):  21.107 ms … 88.421 ms  ┊ GC (min … max): 0.00% … 75.12%
 Time  (median):     21.362 ms              ┊ GC (median):    0.00%
 Time  (mean ± σ):   22.097 ms ±  4.550 ms  ┊ GC (mean ± σ):  2.80% ±  6.42%

  ▃█▇▃ ▂▄▂ ▃▄                                                  
  ████▆███▄███▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▇▁▁▁▁▆▁▄▆▆▁▁▁▁▆▄▁▄▁▄▁▁▁▁▁▆▄▄▄ ▆
  21.1 ms      Histogram: log(frequency) by time      26.2 ms <

 Memory estimate: 8.71 MiB, allocs estimate: 41919.
```
### Policy Run
#### At Every Iteration
```julia
--------------------------------------------------------------------------------------
 Time       Iter       LB           UB           Precision       # Alphas   # Beli [...]

2024-07-22 21:43 UTC, dylan-asmar commented on src/prune.jl
> +        marked_for_deletion = falses(length(Γ_new_idxs))
Updated in [67133d0](https://github.com/JuliaPOMDP/NativeSARSOP.jl/pull/19/commits/67133d0e7cfeadb14d53ba5c0f8966f0d6b14425)

2024-07-22 22:06 UTC, dylan-asmar commented on src/prune.jl
> +        marked_for_deletion = falses(length(Γ_new_idxs))
This change with the other ones suggested helped bring the allocations down to be better than or on par with the original implementation.

2024-07-22 22:08 UTC, dylan-asmar commented
@WhiffleFish I updated the benchmark results after the suggested changes. We are doing WAY better on allocations than before and are better than or on par with the original implementation now. 

I left the conversations open on the change requests. We can resolve the conversation if you are satisfied with the comments/changes.

Let me know if there are any other changes we should consider.

2025-03-01 18:44 UTC, dylan-asmar commented
@WhiffleFish, I am just pinging you again on this one to see if more changes are needed or if you think we can move forward.

2025-03-04 20:50 UTC, WhiffleFish commented on src/prune.jl
> +    prune_strictly_dominated!(tree::SARSOPTree)
Okay cool, thanks for checking. I think trading some allocations for faster speed overall is a reasonable choice.

2025-03-04 20:57 UTC, WhiffleFish commented
There were a couple of things I still wanted to optimize further here but never got around to finishing, so I think this is definitely good to merge now. 

Thanks for the hard work here, Dylan.

2025-03-04 20:57 UTC, merged

2025-03-04 21:07 UTC, dylan-asmar commented
Thoughts on writing them up in an issue? Just a place to track your ideas and potentially implement the performance improvements when we have time?